// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: conn.proto

package conn

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnServiceClient is the client API for ConnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnServiceClient interface {
	Push(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushRsp, error)
}

type connServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnServiceClient(cc grpc.ClientConnInterface) ConnServiceClient {
	return &connServiceClient{cc}
}

func (c *connServiceClient) Push(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushRsp, error) {
	out := new(PushRsp)
	err := c.cc.Invoke(ctx, "/conn.ConnService/push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnServiceServer is the server API for ConnService service.
// All implementations must embed UnimplementedConnServiceServer
// for forward compatibility
type ConnServiceServer interface {
	Push(context.Context, *PushReq) (*PushRsp, error)
	mustEmbedUnimplementedConnServiceServer()
}

// UnimplementedConnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConnServiceServer struct {
}

func (UnimplementedConnServiceServer) Push(context.Context, *PushReq) (*PushRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedConnServiceServer) mustEmbedUnimplementedConnServiceServer() {}

// UnsafeConnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnServiceServer will
// result in compilation errors.
type UnsafeConnServiceServer interface {
	mustEmbedUnimplementedConnServiceServer()
}

func RegisterConnServiceServer(s grpc.ServiceRegistrar, srv ConnServiceServer) {
	s.RegisterService(&ConnService_ServiceDesc, srv)
}

func _ConnService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conn.ConnService/push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnServiceServer).Push(ctx, req.(*PushReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnService_ServiceDesc is the grpc.ServiceDesc for ConnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conn.ConnService",
	HandlerType: (*ConnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "push",
			Handler:    _ConnService_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conn.proto",
}
