// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: conn.proto

package conn

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SigServiceClient is the client API for SigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SigServiceClient interface {
	Push(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushRsp, error)
}

type sigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSigServiceClient(cc grpc.ClientConnInterface) SigServiceClient {
	return &sigServiceClient{cc}
}

func (c *sigServiceClient) Push(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushRsp, error) {
	out := new(PushRsp)
	err := c.cc.Invoke(ctx, "/conn.SigService/push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigServiceServer is the server API for SigService service.
// All implementations must embed UnimplementedSigServiceServer
// for forward compatibility
type SigServiceServer interface {
	Push(context.Context, *PushReq) (*PushRsp, error)
	mustEmbedUnimplementedSigServiceServer()
}

// UnimplementedSigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSigServiceServer struct {
}

func (UnimplementedSigServiceServer) Push(context.Context, *PushReq) (*PushRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedSigServiceServer) mustEmbedUnimplementedSigServiceServer() {}

// UnsafeSigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigServiceServer will
// result in compilation errors.
type UnsafeSigServiceServer interface {
	mustEmbedUnimplementedSigServiceServer()
}

func RegisterSigServiceServer(s grpc.ServiceRegistrar, srv SigServiceServer) {
	s.RegisterService(&SigService_ServiceDesc, srv)
}

func _SigService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conn.SigService/push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigServiceServer).Push(ctx, req.(*PushReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SigService_ServiceDesc is the grpc.ServiceDesc for SigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conn.SigService",
	HandlerType: (*SigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "push",
			Handler:    _SigService_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conn.proto",
}
