// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: sso.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SigServiceClient is the client API for SigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SigServiceClient interface {
	SigIn(ctx context.Context, in *SigReq, opts ...grpc.CallOption) (*Response, error)
	SigOut(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*Response, error)
	Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*Response, error)
	Register(ctx context.Context, in *SigReq, opts ...grpc.CallOption) (*Response, error)
}

type sigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSigServiceClient(cc grpc.ClientConnInterface) SigServiceClient {
	return &sigServiceClient{cc}
}

func (c *sigServiceClient) SigIn(ctx context.Context, in *SigReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SigService/SigIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sigServiceClient) SigOut(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SigService/SigOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sigServiceClient) Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SigService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sigServiceClient) Register(ctx context.Context, in *SigReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SigService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigServiceServer is the server API for SigService service.
// All implementations must embed UnimplementedSigServiceServer
// for forward compatibility
type SigServiceServer interface {
	SigIn(context.Context, *SigReq) (*Response, error)
	SigOut(context.Context, *CheckReq) (*Response, error)
	Check(context.Context, *CheckReq) (*Response, error)
	Register(context.Context, *SigReq) (*Response, error)
	mustEmbedUnimplementedSigServiceServer()
}

// UnimplementedSigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSigServiceServer struct {
}

func (UnimplementedSigServiceServer) SigIn(context.Context, *SigReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigIn not implemented")
}
func (UnimplementedSigServiceServer) SigOut(context.Context, *CheckReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigOut not implemented")
}
func (UnimplementedSigServiceServer) Check(context.Context, *CheckReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSigServiceServer) Register(context.Context, *SigReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSigServiceServer) mustEmbedUnimplementedSigServiceServer() {}

// UnsafeSigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigServiceServer will
// result in compilation errors.
type UnsafeSigServiceServer interface {
	mustEmbedUnimplementedSigServiceServer()
}

func RegisterSigServiceServer(s grpc.ServiceRegistrar, srv SigServiceServer) {
	s.RegisterService(&SigService_ServiceDesc, srv)
}

func _SigService_SigIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigServiceServer).SigIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SigService/SigIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigServiceServer).SigIn(ctx, req.(*SigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigService_SigOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigServiceServer).SigOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SigService/SigOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigServiceServer).SigOut(ctx, req.(*CheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SigService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigServiceServer).Check(ctx, req.(*CheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SigService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigServiceServer).Register(ctx, req.(*SigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SigService_ServiceDesc is the grpc.ServiceDesc for SigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SigService",
	HandlerType: (*SigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SigIn",
			Handler:    _SigService_SigIn_Handler,
		},
		{
			MethodName: "SigOut",
			Handler:    _SigService_SigOut_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _SigService_Check_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _SigService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso.proto",
}
